### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by louisroyer**
And remove intllib support since we use minetest api instead.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Please convert the Italian translation rather than deleting it.

**Comment by louisroyer** [comment]
> Please convert the Italian translation rather than deleting it.

Italian translation is already duplicated in `castle_tapestries.it.tr` (from #9).

**Comment by FaceDeer** [comment]
This change adds french, but loses the polish translations that were already here. Could you convert the polish translation to the new format?

Oh, and while I'm at it, what tools are you using for making these translation files? There's a [thread on the subject of translation toolchains](https://forum.minetest.net/viewtopic.php?f=47&t=23330&p=367304) and the best I've seen is a python script I'm going to have to do some work with to make general-purpose, if you know of something better please let me know. I'd be fine with converting mods over to the new system if the new system was actually as easy to work with as the old system was.

**Comment by louisroyer** [comment]
> This change adds french, but loses the polish translations that were already here. Could you convert the polish translation to the new format?
> 
> Oh, and while I'm at it, what tools are you using for making these translation files? There's a [thread on the subject of translation toolchains](https://forum.minetest.net/viewtopic.php?f=47&t=23330&p=367304) and the best I've seen is a python script I'm going to have to do some work with to make general-purpose, if you know of something better please let me know. I'd be fine with converting mods over to the new system if the new system was actually as easy to work with as the old system was.

I do not understand: in which file are polish translations your are talking about?
To convert `.po` to `.tr`, I am using vim with some substitute commands (and copy-pasting `# textdomain: ` line).
```
:%g/#:.*/d
:%s/msgid "//g
:%s/"\nmsgstr "/=/g
:%s/"\n//g
:%s/\\"/"/g
:%s/\\n/@n/g
```
(the order is significant), but I am not sure it will work on all files .
Also, I can help working on the python script if you need.

**Comment by FaceDeer** [comment]
Argh. Italian, not polish. The .po extention throws me every time. I see it's handled by that other pull, so I'll get this merged in.

I'll see if I can add auto-upgrading of old .po files to that Python script I've been flailing at. But any help would be most welcome, I'm not a Python guy normally.

**Pull request merged**
